# Generated by Django 3.2 on 2021-04-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0003_alter_youtuber_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtuber',
            old_name='sub_count',
            new_name='subs_count',
        ),
    ]
